services:

  nginx:
    build:
      context: .
      dockerfile: dockerfile.nginx-for-fastapi.prod
    container_name: nginx
    ports:
      - "3500:3500"

  node1:
    build:
      context: .
      dockerfile: dockerfile.fastapi-for-nginx.prod
    container_name: node1
    depends_on:
      - nginx
    ports:
      - "800:800"
  
  front:
    build:
      context: .
      dockerfile: dockerfile.nginx-for-frontend
    container_name: front_nginx
    ports:
      - "80:80"